### PR TITLE
expand php version for php 8.0

### PR DESCRIPTION
**Pull request by anggerpradana**
- php 8.0 version support

### CODE REVIEW

**Comment by SonyPradana** [comment]
Don't rush to add support for php 8.0 version, there are some details that need to be improved first. like test cases and issue with deprecated in PHP 8.0.  Php 8.0 version may be supported but does not guarantee full support until a complete test suite is made.

**Comment by anggerpradana** [comment]
i will make test for validate every validate rule, to make sure PR work in php 8.0 too.

**Comment by SonyPradana** [comment]
Okey thanks, create new pull request for validation test. Then merge to this PR

**Comment by anggerpradana** [comment]
sory i have bad commit

**Pull request closed without merging**
